name: GitHub Action Workflow Demo

on:
  push:
    branches:
      - develop

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r Train/requirements.txt

      - name: Run training script
        run: python Train/train_model.py
